version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload && alembic upgrade head
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
